
    create table canchas (
        id bigint generated by default as identity (start with 1),
        estaIluminada boolean,
        nombre varchar(255),
        color_id bigint,
        primary key (id)
    )

    create table colores (
        id bigint generated by default as identity (start with 1),
        descripcion varchar(255),
        primary key (id)
    )

    create table constructores (
        id bigint generated by default as identity (start with 1),
        domicilio varchar(255),
        nombre varchar(255),
        primary key (id)
    )

    create table jugadores (
        id bigint generated by default as identity (start with 1),
        apellido varchar(255),
        domicilio varchar(255),
        nacimiento varbinary(255),
        nombre varchar(255),
        paleta_id bigint,
        primary key (id)
    )

    create table paletas (
        id bigint generated by default as identity (start with 1),
        grosor integer,
        nombre varchar(255),
        color_id bigint,
        constructor_id bigint,
        primary key (id)
    )

    create table participaciones (
        partido_id bigint not null,
        jugador_id bigint not null,
        paleta_id bigint,
        primary key (partido_id, jugador_id)
    )

    create table partidos (
        id bigint generated by default as identity (start with 1),
        cancha_id bigint,
        colorCancha_id bigint,
        reserva_id bigint,
        primary key (id)
    )

    create table reservas (
        id bigint generated by default as identity (start with 1),
        fin_partido varbinary(255),
        inicio_partido varbinary(255),
        cancha_id bigint,
        responsable_id bigint,
        primary key (id)
    )

    alter table canchas 
        add constraint FK_7simpd9836xes455cr5vnt7kt 
        foreign key (color_id) 
        references colores

    alter table jugadores 
        add constraint FK_qhw5kcnedfre5mqxg1x7tsv47 
        foreign key (paleta_id) 
        references paletas

    alter table paletas 
        add constraint FK_douiichvo5uf38x9b5be2m1b5 
        foreign key (color_id) 
        references colores

    alter table paletas 
        add constraint FK_iou34996tq539puyuprhfqqqy 
        foreign key (constructor_id) 
        references constructores

    alter table participaciones 
        add constraint FK_8fvppmamjcwh0gcsikkvlrxkr 
        foreign key (partido_id) 
        references partidos

    alter table participaciones 
        add constraint FK_5g3cyci40hi54gy1q76398pe7 
        foreign key (jugador_id) 
        references jugadores

    alter table participaciones 
        add constraint FK_9aqxq6urad0w5hujxo58ybrg8 
        foreign key (paleta_id) 
        references paletas

    alter table partidos 
        add constraint FK_4e5f4a7gjg056i60wfgjspx8e 
        foreign key (cancha_id) 
        references canchas

    alter table partidos 
        add constraint FK_7337yaygk0ym3btrfc332rrat 
        foreign key (colorCancha_id) 
        references colores

    alter table partidos 
        add constraint FK_f5ufrt3pgqx6wv2dti9yq6d2a 
        foreign key (reserva_id) 
        references reservas

    alter table reservas 
        add constraint FK_crhvn3qf3blvpi0loeuteodd 
        foreign key (cancha_id) 
        references canchas

    alter table reservas 
        add constraint FK_1j0nmeck9gkndqi5156t8le6g 
        foreign key (responsable_id) 
        references jugadores
